config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  root 'simple_pages#landing_page'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.includes(:product).all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
   def landing_page
     @featured_product = Product.first
     @products = Product.limit(3)
   end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="fixed-bottom">
    <small>
      &copy; 2018 Bike Berlin
      </small>
      <nav>
        <ul>
        <li> <%= link_to "About", simple_pages_about_path, class: "links" %> </li>
        <li> <%= link_to "Contact", simple_pages_contact_path, class: "links" %> </li>
         </ul>
       </nav>   
  </footer>
 </div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Bike Berlin", root_path, class: "navbar-brand", id: "logo" %>
  <div class="container-fluid">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "Home", root_path, class: "links
links" %>
      </li>
      <li class="nav-item">
      <%= link_to "Products", products_path, class: "links
links" %>
      </li>
      <li class="nav-item"><%= link_to "Orders", orders_path, class: "links
links" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", simple_pages_about_path, class: "links
links" %>
      </li>
      <li class="nav-item">
      <%= link_to "Contact", simple_pages_contact_path, class: "links
links" %>
      </li>
    </ul>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="ut8">
    <title>Bike Berlin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    
<%= render 'layouts/navigation' %>
<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="order-content">
  <% @orders.each do |order| %>
    <div class="col-sm">
      <h1>
        Order # <%= order.id %>:
        <%= link_to order.product.name, order %>
      </h1>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div><!-- /col -->
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="container order-content">
  <h2>Order Information</h2>
  <strong>Order ID: </strong><%= @order.id %>
  <strong>Product Name: </strong><%= @order.product.name %>
  <strong>Product Price: </strong><%= number_to_currency(@order.product.price/100.to_f) %>
  <strong>Total Price: </strong><%= number_to_currency(@order.total/100.to_f) %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :colour %><br>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/products/_product.html.erb
<div class="col-sm-12 col-md-6 col-lg">
   <div  class="productgallery-image"><%= image_tag(product.image_url, class: "img-fluid") %></div>
   <div class="productgallery-info">
     <a href="#"><p class="productgallery-name"><%= product.name %></p></a>
     <p class="productgallery-decription"><%= product.description %></p>
     <p class="productgallery-color">Color: <%= product.colour %></p>
     <p class="productgallery-price"><%= product.price %>€</p>
   </div>

   <div class="productgallery-edit">
     <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
     <p class="horizontal-line"><%= link_to 'Show', product %></p>
     <p class="horizontal-line"><%= link_to 'Edit', edit_product_path(product) %></p>
   </div>
 </div><!-- /col -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>  

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>  

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide landing-carousel" data-ride="carousel">

   <!-- indicators -->
   <ol class="carousel-indicators">
     <% @products.each_with_index do |product| %>
     <li class="link<%= " active" if product == @products.first %>">
     <li data-target="#carouselExampleIndicators"></li>
     <% end %>
   </ol>

   <!-- wrapper for slides -->
   <div class="carousel-inner">
     <% @products.each do |product| %>
     <div class="carousel-item<%= " active" if product == @products.first %>">
       <%= image_tag(product.image_url, class: "img-fluid jumbotron-images") %>
       <div class="carousel-caption d-none d-md-block">
         <h5><%= product.name %></h5>
       </div>
     </div>
     <% end %>
   </div>

 <!-- controls -->
 <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
   <span class="carousel-control-prev-icon" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
   <span class="carousel-control-next-icon" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
   </div>
 </div>

app/views/simple_pages/about.html.erb
<h1>Bike Berlin – Online Bike Shop & Stores Nationwide</h1>
  <p>Enjoy flying up hills? Start with our range of road bikes. Or if it’s all about tracks and trails, head to our mountain bikes for a mix of hardtail and full suspension machines</p>

app/views/simple_pages/contact.html.erb
<h1>Bike Berlin - Contact Us</h1>
  <p>Köpenicker Str. 126,<br>
    10179 Berlin,<br>
    Germany</p>

app/views/simple_pages/index.html.erb
<div class="center jumbotron">
  <h1> Bike Berlin <h1>
  <%= link_to "Sign up now", simple_pages_contact_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/simple_pages/landing_page.html.erb
<h2>Featured Product:</h2>
 <div class="index-content">
   <h1>Welcome to Unsplash</h1>
   <p class="intro-text">Some beautiful and breathe taking images from Unsplash</p>
   <%= render 'simple_pages/carousel' %>
 </div><!--/index-content -->